spring:
#  h2:
#    console.enabled: true
  datasource:
    url: jdbc:h2:C:\Users\USER\IdeaProjects\java-filmorate\.github\db\filmorate;
#    url: jdbc:h2:mem:filmorate;
    driver-class name: org.h2.Driver
    username: sa
    password: password

  sql:
    init:
      mode: always